### ISSUE TITLE
Example to register new Users

### ISSUE THREAD

**Issue by s3ppo** [SoftInstigate/restheart-examples#1]
as spoken on gitter, would be cool the get an example for this. :)

**Comment by ujibang** [comment]
Hi @s3ppo ,

will do but these days are very busy, will probably make it next week.

**Comment by ujibang** [comment]
Hi @s3ppo 

I started it https://github.com/SoftInstigate/restheart-examples/tree/master/user-signup

It's is still incomplete and will progress it next week. The readme describes the process, let me know if it makes sense for your use case...

**Comment by ujibang** [comment]
Hi @s3ppo,

I finally found time to complete the user-signup example. Hope you'll like it!

See more at https://github.com/SoftInstigate/restheart-examples/tree/master/user-signup/README.md

**Comment by s3ppo** [comment]
Thanks a lot for your effort ;)
